name: dani
favicon: null
layout_spectrum: 0.8593145171180367
typography_spectrum: 0.46185415936633945
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.44649788178503513
  lightness: 0.29537179274484515
  saturation: 0.5426066815853119
  rhythmicContrast: 0.20504424907267094
purpose: []
